import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = '/api';
const roles = ['ADMIN','MANAGER','TECHNICIAN','OFFICE','EMPLOYEE'];
function useApi(){
 const [token,setToken]=useState(localStorage.attendlyToken||'');
 const request=async(path,opts={})=>{ const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opts.headers||{})}}); const data=await r.json().catch(()=>null); if(!r.ok) throw new Error(data?.error||'Request failed'); return data; };
 return {token,setToken:t=>{localStorage.attendlyToken=t;setToken(t)},request,logout:()=>{localStorage.removeItem('attendlyToken');setToken('')}};
}
function Login({api}){ const [email,setEmail]=useState('admin@attendly.local'),[password,setPassword]=useState('admin123!'),[err,setErr]=useState(''); async function submit(e){e.preventDefault();setErr('');try{const d=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}).then(r=>r.json().then(j=>r.ok?j:Promise.reject(j)));api.setToken(d.token)}catch(e){setErr(e.error||e.message)}} return <div className="login"><form onSubmit={submit} className="card auth"><h1>Attendly</h1><p>Production admin login</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<b className="err">{err}</b>}<button>Sign in</button><small>Seed login: admin@attendly.local / admin123!</small></form></div> }
function App(){ const api=useApi(); const [tab,setTab]=useState('Dashboard'); if(!api.token) return <Login api={api}/>; return <div><aside><h2>Attendly</h2>{['Dashboard','Kiosk','Employees','Punches','Time Off','Reports'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}<button onClick={api.logout}>Logout</button></aside><main>{tab==='Dashboard'&&<Dashboard api={api}/>} {tab==='Kiosk'&&<Kiosk/>} {tab==='Employees'&&<Employees api={api}/>} {tab==='Punches'&&<Punches api={api}/>} {tab==='Time Off'&&<TimeOff api={api}/>} {tab==='Reports'&&<Reports api={api}/>}</main></div> }
function Dashboard({api}){ const [d,setD]=useState(null); useEffect(()=>{api.request('/dashboard').then(setD)},[]); return <><h1>Admin Dashboard</h1><div className="grid metrics">{[['Active Employees',d?.activeEmployees],['Today’s Punches',d?.todaysPunches],['Pending Requests',d?.pendingRequests],['Total Employees',d?.totalEmployees]].map(([k,v])=><div className="card"><span>{k}</span><strong>{v??'—'}</strong></div>)}</div><div className="card"><h3>Production-ready pieces included</h3><p>PostgreSQL database, Prisma migrations, Express API, JWT admin auth, hashed employee PINs, audit log, Docker Compose, reports, CSV export, and deployable static frontend.</p></div></> }
function Kiosk(){ const [pin,setPin]=useState(''),[msg,setMsg]=useState(''); async function punch(){setMsg('');try{const r=await fetch(API+'/kiosk/punch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});const d=await r.json(); if(!r.ok) throw new Error(d.error); setMsg(`${d.employee.name} ${d.punch.type.replace('_',' ').toLowerCase()} at ${new Date(d.punch.occurredAt).toLocaleString()}`); setPin('')}catch(e){setMsg(e.message)}} return <><h1>Employee Kiosk</h1><div className="card kiosk"><input placeholder="Employee PIN" value={pin} onChange={e=>setPin(e.target.value)} type="password"/><button onClick={punch}>Clock In / Out</button><p>{msg}</p></div></> }
function Employees({api}){ const empty={name:'',role:'EMPLOYEE',pin:'',status:'ACTIVE',payType:'Hourly',vacationHours:0,sickHours:0}; const [items,setItems]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null); const load=()=>api.request('/employees').then(setItems); useEffect(load,[]); async function save(e){e.preventDefault(); const method=edit?'PUT':'POST', path=edit?`/employees/${edit}`:'/employees'; await api.request(path,{method,body:JSON.stringify(form)}); setEdit(null); setForm(empty); load(); } return <><h1>Employees</h1><form className="card form" onSubmit={save}><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option>{r}</option>)}</select><input placeholder="New PIN" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})}/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select><input type="number" value={form.vacationHours} onChange={e=>setForm({...form,vacationHours:e.target.value})}/><input type="number" value={form.sickHours} onChange={e=>setForm({...form,sickHours:e.target.value})}/><button>{edit?'Update':'Add'} employee</button></form><Table rows={items} cols={['name','role','status','payType','pinLast4','vacationHours','sickHours']} actions={r=><><button onClick={()=>{setEdit(r.id);setForm({...r,pin:''})}}>Edit</button><button onClick={()=>api.request('/employees/'+r.id,{method:'DELETE'}).then(load)}>Deactivate</button></>}/></> }
function Punches({api}){ const [rows,setRows]=useState([]); useEffect(()=>{api.request('/punches').then(setRows)},[]); return <><h1>Punches</h1><Table rows={rows.map(p=>({employee:p.employee?.name,type:p.type,occurredAt:new Date(p.occurredAt).toLocaleString(),note:p.note||''}))} cols={['employee','type','occurredAt','note']}/></> }
function TimeOff({api}){ const [employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[form,setForm]=useState({employeeId:'',startDate:'',endDate:'',hours:8,type:'Vacation',reason:''}); const load=()=>{api.request('/employees').then(e=>{setEmployees(e); setForm(f=>({...f,employeeId:f.employeeId||e[0]?.id||''}))});api.request('/time-off').then(setRows)}; useEffect(load,[]); async function submit(e){e.preventDefault();await api.request('/time-off',{method:'POST',body:JSON.stringify(form)});load()} return <><h1>Time Off</h1><form className="card form" onSubmit={submit}><select value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{employees.map(e=><option value={e.id}>{e.name}</option>)}</select><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/><input type="number" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Vacation</option><option>Sick</option><option>Personal</option></select><input placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button>Request</button></form><Table rows={rows.map(r=>({id:r.id,employee:r.employee?.name,type:r.type,hours:r.hours,status:r.status,start:new Date(r.startDate).toLocaleDateString(),end:new Date(r.endDate).toLocaleDateString()}))} cols={['employee','type','hours','status','start','end']} actions={r=><><button onClick={()=>api.request(`/time-off/${r.id}/status`,{method:'PATCH',body:JSON.stringify({status:'APPROVED'})}).then(load)}>Approve</button><button onClick={()=>api.request(`/time-off/${r.id}/status`,{method:'PATCH',body:JSON.stringify({status:'DENIED'})}).then(load)}>Deny</button></>}/></> }
function Reports({api}){ const [data,setData]=useState(null),[from,setFrom]=useState(new Date(Date.now()-14*864e5).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)); const load=()=>api.request(`/reports/payroll?from=${from}&to=${to}`).then(setData); useEffect(load,[]); return <><h1>Reports</h1><div className="card toolbar"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button onClick={load}>Run</button><a className="button" href={`${API}/reports/export.csv?from=${from}&to=${to}`}>CSV Export</a></div><Table rows={data?.rows||[]} cols={['name','role','hours','punches']}/></> }
function Table({rows=[],cols=[],actions}){ return <div className="card table"><table><thead><tr>{cols.map(c=><th>{c}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td>{String(r[c]??'')}</td>)}{actions&&<td className="actions">{actions(r)}</td>}</tr>)}</tbody></table></div> }

createRoot(document.getElementById('root')).render(<App/>);
