const express=require('express');const {Pool}=require('pg');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();app.use(express.json({limit:'1mb'}));app.use(express.static('public'));
const PORT=process.env.PORT||3000, SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('railway')?{rejectUnauthorized:false}:undefined}):null;
let mem={employees:[],punches:[],pto:[],balances:[],audit:[],users:[]};
const employees=[['Miguel Ortiz','Manager','3874','Active','Office','Full-Time','miguel@company.com','(555) 210-1001'],['Samantha Lee','Office','1936','Active','Office','Full-Time','samantha@company.com','(555) 210-1002'],['Derrick Moore','Technician','8421','Active','Field','Full-Time','derrick@company.com','(555) 210-1003'],['Ava Johnson','Technician','6109','Active','Field','Full-Time','ava@company.com','(555) 210-1004'],['Ethan Parker','Technician','4792','Active','Field','Full-Time','ethan@company.com','(555) 210-1005'],['Olivia Kim','Office','2548','Active','Admin','Part-Time','olivia@company.com','(555) 210-1006'],['Noah Williams','Technician','7315','Active','Field','Full-Time','noah@company.com','(555) 210-1007'],['Mia Thompson','Technician','9062','Active','Field','Full-Time','mia@company.com','(555) 210-1008'],['James Garcia','Manager','3187','Active','Operations','Full-Time','james@company.com','(555) 210-1009'],['Sophia Brown','Technician','6650','Active','Field','Part-Time','sophia@company.com','(555) 210-1010'],['Liam Davis','Technician','5284','Inactive','Field','Full-Time','liam@company.com','(555) 210-1011']];
async function q(sql,p=[]){if(!pool)throw Error('no db');return (await pool.query(sql,p)).rows}
async function init(){if(!pool){mem.employees=employees.map((e,i)=>({id:i+1,name:e[0],role:e[1],pin:e[2],status:e[3],department:e[4],pay_type:e[5],email:e[6],phone:e[7],created_at:new Date()}));mem.balances=mem.employees.map(e=>({employee_id:e.id,vacation:80,sick:40,personal:16}));mem.users=[{email:'admin@attendly.local',password:bcrypt.hashSync('admin123!',10)}];return}
await q(`create table if not exists users(id serial primary key,email text unique,password text not null,role text default 'Admin');
create table if not exists employees(id serial primary key,name text not null,role text not null,pin text unique not null,status text default 'Active',department text default 'Field',pay_type text default 'Full-Time',email text default '',phone text default '',created_at timestamptz default now());
create table if not exists punches(id serial primary key,employee_id int references employees(id) on delete cascade,clock_in timestamptz not null,clock_out timestamptz,notes text default '');
create table if not exists pto(id serial primary key,employee_id int references employees(id) on delete cascade,type text,start_date date,end_date date,hours numeric default 8,status text default 'Pending',reason text default '',created_at timestamptz default now());
create table if not exists balances(employee_id int primary key references employees(id) on delete cascade,vacation numeric default 80,sick numeric default 40,personal numeric default 16);
create table if not exists audit(id serial primary key,action text,detail text,created_at timestamptz default now());`);
let u=await q('select id from users limit 1');if(!u.length)await q('insert into users(email,password) values($1,$2)',[process.env.ADMIN_EMAIL||'admin@attendly.local',bcrypt.hashSync(process.env.ADMIN_PASSWORD||'admin123!',10)]);
let c=await q('select count(*)::int c from employees');if(!c[0].c){for(const e of employees){let r=await q('insert into employees(name,role,pin,status,department,pay_type,email,phone) values($1,$2,$3,$4,$5,$6,$7,$8) returning id',e);await q('insert into balances(employee_id) values($1)',[r[0].id])}}
}
function auth(req,res,next){let h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace('Bearer ',''),SECRET);next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
function memId(a){return Math.max(0,...a.map(x=>x.id||0))+1}
app.post('/api/login',async(req,res)=>{let {email,password}=req.body;if(pool){let r=await q('select * from users where email=$1',[email]);if(r[0]&&bcrypt.compareSync(password,r[0].password))return res.json({token:jwt.sign({email,role:r[0].role},SECRET),email})}else{let u=mem.users.find(u=>u.email===email);if(u&&bcrypt.compareSync(password,u.password))return res.json({token:jwt.sign({email},SECRET),email})}res.status(401).json({error:'Invalid login'})});
app.get('/api/data',auth,async(req,res)=>{let data=pool?{employees:await q('select * from employees order by status,name'),punches:await q('select p.*,e.name employee,e.role from punches p join employees e on e.id=p.employee_id order by coalesce(clock_out,clock_in) desc limit 500'),pto:await q('select p.*,e.name employee from pto p join employees e on e.id=p.employee_id order by created_at desc'),balances:await q('select b.*,e.name employee from balances b join employees e on e.id=b.employee_id order by e.name')}:mem;res.json(data)});
app.post('/api/employees',auth,async(req,res)=>{let b=req.body;if(pool){let r=await q('insert into employees(name,role,pin,status,department,pay_type,email,phone) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[b.name,b.role,b.pin,b.status||'Active',b.department||'',b.pay_type||'Full-Time',b.email||'',b.phone||'']);await q('insert into balances(employee_id) values($1)',[r[0].id]);return res.json(r[0])}b.id=memId(mem.employees);mem.employees.push(b);mem.balances.push({employee_id:b.id,vacation:80,sick:40,personal:16});res.json(b)});
app.put('/api/employees/:id',auth,async(req,res)=>{let id=+req.params.id,b=req.body;if(pool)return res.json((await q('update employees set name=$1,role=$2,pin=$3,status=$4,department=$5,pay_type=$6,email=$7,phone=$8 where id=$9 returning *',[b.name,b.role,b.pin,b.status,b.department,b.pay_type,b.email,b.phone,id]))[0]);Object.assign(mem.employees.find(e=>e.id==id),b);res.json({ok:true})});
app.post('/api/punch',async(req,res)=>{let {pin,employee_id,notes}=req.body;let emp;if(pool){emp=(await q('select * from employees where pin=$1 or id=$2',[pin||'',employee_id||0]))[0];if(!emp)return res.status(404).json({error:'PIN not found'});let open=(await q('select * from punches where employee_id=$1 and clock_out is null order by id desc limit 1',[emp.id]))[0];if(open){await q('update punches set clock_out=now(),notes=$2 where id=$1',[open.id,notes||'']);return res.json({message:`${emp.name} clocked out`})}await q('insert into punches(employee_id,clock_in,notes) values($1,now(),$2)',[emp.id,notes||'']);return res.json({message:`${emp.name} clocked in`})}emp=mem.employees.find(e=>e.pin==pin||e.id==employee_id);if(!emp)return res.status(404).json({error:'PIN not found'});let open=mem.punches.find(p=>p.employee_id==emp.id&&!p.clock_out);if(open){open.clock_out=new Date();return res.json({message:`${emp.name} clocked out`})}mem.punches.push({id:memId(mem.punches),employee_id:emp.id,employee:emp.name,clock_in:new Date(),clock_out:null,notes:notes||''});res.json({message:`${emp.name} clocked in`})});
app.post('/api/pto',async(req,res)=>{let b=req.body;if(pool){let emp=(await q('select id,name from employees where pin=$1 or id=$2',[b.pin||'',b.employee_id||0]))[0];if(!emp)return res.status(404).json({error:'Employee not found'});let r=await q('insert into pto(employee_id,type,start_date,end_date,hours,reason,status) values($1,$2,$3,$4,$5,$6,$7) returning *',[emp.id,b.type,b.start_date,b.end_date,b.hours||8,b.reason||'',b.status||'Pending']);return res.json(r[0])}res.json({ok:true})});
app.put('/api/pto/:id',auth,async(req,res)=>{let id=+req.params.id,{status}=req.body;if(pool){let r=(await q('update pto set status=$1 where id=$2 returning *',[status,id]))[0];if(status==='Approved'&&r){let col=r.type==='Sick'?'sick':r.type==='Personal'?'personal':'vacation';await q(`update balances set ${col}=greatest(0,${col}-$1) where employee_id=$2`,[r.hours,r.employee_id])}return res.json(r)}res.json({ok:true})});
app.delete('/api/punches/:id',auth,async(req,res)=>{if(pool)await q('delete from punches where id=$1',[req.params.id]);else mem.punches=mem.punches.filter(p=>p.id!=req.params.id);res.json({ok:true})});
app.get('*',(req,res)=>res.sendFile(__dirname+'/public/index.html'));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Attendly running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
